### ISSUE TITLE
Need to re-order genes on oncomap

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/JHU-biobank#15]
We're trying to send the manuscript around today, but CHristine wants an updated list of genes.

Can we replace the genes with the following:
NF1

TP53

CDKN2A

EED

SUZ12

EZH2

CHD4

EPC1

ASTE1

DAXX

ATRX

PCLO

MTAP

PREX2

NCOA2

BCL2L1

TYK2

BRAF

EGFR

LRP1B

MSH3

**Comment by jaybee84** [comment]
Regenerated files in PR#17
