### ISSUE TITLE
add docker cnv instructions

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/JHU-biobank#20]
Can you add instructions (no need to be super detailed) for running the cnv docker to the README after we merge in PR #19 ?

**Comment by jaybee84** [comment]
Are you referring to the Readme for the repo?

**Comment by allaway** [comment]
Yep! I added a header in my latest PR.

**Comment by jaybee84** [comment]
:) I had already added the instructions towards the end of the Readme... Moved them up in PR #21  :)

**Comment by allaway** [comment]
Whoops, didn't see that. Thanks!
