### ISSUE TITLE
Exome seq figures cannot be generated from Rmd

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/JHU-biobank#8]
I tried to run the RMd so that we can share the html file on github and I was unable to run. the error I get is:
![image](https://user-images.githubusercontent.com/1847866/66875359-dfacfb80-ef62-11e9-890a-a915d78512d5.png)

Can you add in some synapse commands to allow this to be run by anyone?

**Comment by sgosline** [comment]
It'd be nice to not require maf files to generate these - can you use the table and reformat them to generate the figures? this way we can easily swap out the new tool as well.

**Comment by jaybee84** [comment]
New pull request with Rmd file regenerated to work with Synapse table housing exomeseq data. Currently the file works with the public table. I will change it to reflect all JHU Biobank data once PR is reviewed.

review requested : @sgosline

**Comment by allaway** [comment]
Sidenote - can you double check the dockerfiles in my pr (#11) to make sure they have the necessary packages, if you have added anything new to the Rmd?

**Comment by jaybee84** [comment]
@allaway: I have not added anything to the demo Rmd file, but the Scidata_figures.Rmd file has library(wesanderson) which is absent in the dockerfile. Otherwise LGTM.

**Comment by allaway** [comment]
> @allaway: I have not added anything to the demo Rmd file, but the Scidata_figures.Rmd file has library(wesanderson) which is absent in the dockerfile. Otherwise LGTM.

This file is not currently part of the docker container (scidata_figures). Is it supposed to be?

**Comment by jaybee84** [comment]
Hmmm... maybe not! I guess the docker containers are only to run the demo files explaining the dataset and not really for regenerating the figures. So we dont need to include this file in the container ! :)

**Comment by allaway** [comment]
Well....I guess then I'd ask why aren't we creating a docker container to
help recreate the figures?
Maybe we could use the R demo for a dual purpose? I mean, if we're creating
3 docker containers for this publication, at least one of them should be
able to produce the paper figures :)

It would require some restructuring of the repository.

**Comment by jaybee84** [comment]
Oops! missed replying to this earlier! 
I would be on board about creating a docker for reproducing the figures ... :)

**Comment by allaway** [comment]
OK, let's add all of the analysis to the R_demos docker container.

**Comment by allaway** [comment]
Closed by #19.
